PACKAGE_NAME="pps-gen-gpio"
PACKAGE_VERSION="0.1"
MAKE="make -C src/ KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C src/ clean"
BUILT_MODULE_NAME[0]="pps_gen_gpio"
BUILT_MODULE_LOCATION="src/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/other"
AUTOINSTALL=yes
